import { CHANNEL } from "./enums"

export const CHANNEL_SIZE: Record<CHANNEL, number> = {
	[CHANNEL.AI1]: 12,
	[CHANNEL.AI2]: 12,
	[CHANNEL.AI3]: 12,
	[CHANNEL.AI4]: 12,
	[CHANNEL.AI5]: 12,
	[CHANNEL.AI6]: 12,
	[CHANNEL.AX1]: 24,
	[CHANNEL.AX2]: 24,
	[CHANNEL.I1]: 1,
	[CHANNEL.I2]: 1,
	[CHANNEL.O1]: 1,
	[CHANNEL.O2]: 1
}
